collections:
  testjobs:

defaults:
  - scope:
      path: ""
      type: "jobs"
    values:
      layout: "job"


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 4 versions

sass:
  style: compressed
  quiet_deps: true